services:
  app:
    image: ghcr.io/mightyduke/lunch-menu:latest
    restart: always
    ports:
      - 127.0.0.1:8000:80
    environment:
      LUNCH_MENU_ESTABLISHMENTS: "[bo-asi, paleta, blesk, hodonanka, pasta-a-fidli, mb-restaurace, delphi, u-zlateho-jarouse, toni, pho-bo, taj-mahal]"
      LUNCH_MENU_CACHE_URL: "redis://redis"
      LUNCH_MENU_CACHE_EXPIRATION: "600"
      LUNCH_MENU_CRAWLER_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"
  redis:
    image: redis:latest
    restart: always
